server.port=8093
server.servlet.context-path=/DSA-NoSQL-MongoDBService/rest

mongodb.data.source.DB_URL=mongodb://127.0.0.1:27018
mongodb.data.source.database=olist_mongo

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis
