server.port=8097
server.servlet.context-path=/DSA-DOC-CSVService/rest

# Relative path from the service directory to the project root
csv.data.source.file.path=../olist_orders_dataset.csv

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis
