spring.application.name=fdb-api

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Swagger config
springdoc.swagger-ui.path=/swagger-ui.html
