server.port=9990
server.servlet.context-path=/DSA-SparkSQL-Service
server.servlet.session.persistent=false

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=spark
spring.security.user.password=sql

# Spark SQL REST features: enable/disable RESTEnabledSQLService service
sparksql.rest.enabled=true

# Generating endpoints for SparkSQL Views with AutoRESTViewService service
# on | off | restricted
sparksql.autorest.mode=restricted
# on mode template: http://localhost:9990/DSA-SparkSQL-Service/rest/view/{VIEW_NAME}
# restricted mode requires:
# ALTER VIEW <viewName> SET TBLPROPERTIES('AUTOREST' = "/module-path/<viewName>");
# Example:
# ALTER VIEW OLAP_DIM_CUSTS_CITIES_DEPTS SET TBLPROPERTIES('AUTOREST' = "olap/dim/custs_cities_depts");
# restricted template http://localhost:9990/DSA-SparkSQL-Service/rest/view/<view-sub-path>

